import type { Metadata } from "next";
import { Jura } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import Footer from "./components/Footer";
import LayoutHeader from "./components/LayoutHeader";

const jura = Jura({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-jura",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jura.className} bg-white`}>
      <body className="min-h-full flex flex-col">
        <LayoutHeader />
        <ReduxProvider>{children}</ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
